/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Passport {
  address?: string;
  dateOfBirth?: string;
  dateOfExpiry?: string;
  dateOfIssue?: string;
  firstName?: string;
  id?: number;
  issuingAuthority?: string;
  lastName?: string;
  nationality?: string;
  occupation?: string;
  owner?: User;
  passportNumber?: number;
  placeOfBirth?: string;
  primaryPassport?: boolean;
  sex?: string;
}
