/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  email?: string;
  firstName?: string;
  id?: string;
  lastName?: string;
  role?: 'ROLE_MEMBER' | 'ROLE_PMANAGER' | 'ROLE_OFFICER' | 'ROLE_TMANAGER' | 'ROLE_HEAD_MARKET';
  username?: string;
}
