/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TravelRequest } from '../../models/travel-request';

export interface GetByStatus1$Params {
  status: string;
}

export function getByStatus1(http: HttpClient, rootUrl: string, params: GetByStatus1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TravelRequest>>> {
  const rb = new RequestBuilder(rootUrl, getByStatus1.PATH, 'get');
  if (params) {
    rb.path('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TravelRequest>>;
    })
  );
}

getByStatus1.PATH = '/api/validation-travels/status/{status}';
