/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TravelRequest } from '../../models/travel-request';

export interface ValidateStep11$Params {
  id: number;
  approved: boolean;
}

export function validateStep11(http: HttpClient, rootUrl: string, params: ValidateStep11$Params, context?: HttpContext): Observable<StrictHttpResponse<TravelRequest>> {
  const rb = new RequestBuilder(rootUrl, validateStep11.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('approved', params.approved, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TravelRequest>;
    })
  );
}

validateStep11.PATH = '/api/validation-travels/step1/{id}';
