/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Invoice } from '../../models/invoice';

export interface GetInvoiceByTravel$Params {
  travelRequestId: number;
}

export function getInvoiceByTravel(http: HttpClient, rootUrl: string, params: GetInvoiceByTravel$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
  const rb = new RequestBuilder(rootUrl, getInvoiceByTravel.PATH, 'get');
  if (params) {
    rb.path('travelRequestId', params.travelRequestId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Invoice>;
    })
  );
}

getInvoiceByTravel.PATH = '/api/invoices/travel/{travelRequestId}';
