/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TravelRequest } from '../../models/travel-request';

export interface CreateTravelRequest$JsonCharsetUtf8$Params {
      body: TravelRequest
}

export function createTravelRequest$JsonCharsetUtf8(http: HttpClient, rootUrl: string, params: CreateTravelRequest$JsonCharsetUtf8$Params, context?: HttpContext): Observable<StrictHttpResponse<TravelRequest>> {
  const rb = new RequestBuilder(rootUrl, createTravelRequest$JsonCharsetUtf8.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json;charset=UTF-8');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TravelRequest>;
    })
  );
}

createTravelRequest$JsonCharsetUtf8.PATH = '/api/travel-requests/create';
