/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TravelRequest } from '../../models/travel-request';

export interface GetTravelRequest$Params {
  id: number;
}

export function getTravelRequest(http: HttpClient, rootUrl: string, params: GetTravelRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<TravelRequest>> {
  const rb = new RequestBuilder(rootUrl, getTravelRequest.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TravelRequest>;
    })
  );
}

getTravelRequest.PATH = '/api/travel-requests/get/{id}';
