/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TravelRequest } from '../../models/travel-request';

export interface GetAllTravelRequests$Params {
}

export function getAllTravelRequests(http: HttpClient, rootUrl: string, params?: GetAllTravelRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TravelRequest>>> {
  const rb = new RequestBuilder(rootUrl, getAllTravelRequests.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context }) // <- json au lieu de blob
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TravelRequest>>;
    })
  );
}

getAllTravelRequests.PATH = '/api/travel-requests/all';
