/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { VisaRequestControllerService } from './services/visa-request-controller.service';
export { PassportControllerService } from './services/passport-controller.service';
export { AuthControllerService } from './services/auth-controller.service';
