/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VisaRequest } from '../../models/visa-request';

export interface CreateVisaRequest$Params {
  passportId: number;
      body: VisaRequest
}

export function createVisaRequest(http: HttpClient, rootUrl: string, params: CreateVisaRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<VisaRequest>> {
  const rb = new RequestBuilder(rootUrl, createVisaRequest.PATH, 'post');
  if (params) {
    rb.query('passportId', params.passportId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VisaRequest>;
    })
  );
}

createVisaRequest.PATH = '/api/visa-requests/create';
