/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VisaRequest } from '../../models/visa-request';

export interface GetVisaRequestById$Params {
  id: number;
}

export function getVisaRequestById(http: HttpClient, rootUrl: string, params: GetVisaRequestById$Params, context?: HttpContext): Observable<StrictHttpResponse<VisaRequest>> {
  const rb = new RequestBuilder(rootUrl, getVisaRequestById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VisaRequest>;
    })
  );
}

getVisaRequestById.PATH = '/api/visa-requests/{id}';
