/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VisaRequest } from '../../models/visa-request';

export interface UpdateVisaRequest$Params {
  id: number;
      body: VisaRequest
}

export function updateVisaRequest(http: HttpClient, rootUrl: string, params: UpdateVisaRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<VisaRequest>> {
  const rb = new RequestBuilder(rootUrl, updateVisaRequest.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VisaRequest>;
    })
  );
}

updateVisaRequest.PATH = '/api/visa-requests/update/{id}';
