/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VisaRequest } from '../../models/visa-request';

export interface GetByStatus$Params {
  status: string;
}

export function getByStatus(http: HttpClient, rootUrl: string, params: GetByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<VisaRequest>>> {
  const rb = new RequestBuilder(rootUrl, getByStatus.PATH, 'get');
  if (params) {
    rb.path('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<VisaRequest>>;
    })
  );
}

getByStatus.PATH = '/api/validation-visas/status/{status}';
